aliases: []
creation_timestamp: 1735930801191
current_stage: None
description: null
last_updated_timestamp: 1735930801191
name: sentiment_analysis_pipeline
run_id: ff72d53e236f45759dbbb48b59742960
run_link: null
source: file:///content/Practica/mlflow/279798638289980499/ff72d53e236f45759dbbb48b59742960/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///content/Practica/mlflow/279798638289980499/ff72d53e236f45759dbbb48b59742960/artifacts/random_forest_model
user_id: null
version: 1
