aliases: []
creation_timestamp: 1735932487062
current_stage: None
description: null
last_updated_timestamp: 1735932487062
name: sentiment_analysis_pipeline
run_id: 633bdf4c75194b9eb7a20cf01f78829e
run_link: null
source: file:///content/Practica/mlflow/150594715055963914/633bdf4c75194b9eb7a20cf01f78829e/artifacts/sentiment_analysis
status: READY
status_message: null
storage_location: file:///content/Practica/mlflow/150594715055963914/633bdf4c75194b9eb7a20cf01f78829e/artifacts/sentiment_analysis
user_id: null
version: 1
