aliases: []
creation_timestamp: 1743440619273
current_stage: None
description: null
last_updated_timestamp: 1743440619273
name: sentiment_analysis_pipeline
run_id: edaacc0cd1664192a1e944c2c45e3474
run_link: null
source: file:///content/Practica/mlflow/518894292751876995/edaacc0cd1664192a1e944c2c45e3474/artifacts/sentiment_analysis
status: READY
status_message: null
storage_location: file:///content/Practica/mlflow/518894292751876995/edaacc0cd1664192a1e944c2c45e3474/artifacts/sentiment_analysis
user_id: null
version: 4
