aliases: []
creation_timestamp: 1735931007111
current_stage: None
description: null
last_updated_timestamp: 1735931007111
name: sentiment_analysis_pipeline
run_id: d0bf72752d0e448c932f373cb2900ab8
run_link: null
source: file:///content/Practica/mlflow/279798638289980499/d0bf72752d0e448c932f373cb2900ab8/artifacts/sentiment_analysis
status: READY
status_message: null
storage_location: file:///content/Practica/mlflow/279798638289980499/d0bf72752d0e448c932f373cb2900ab8/artifacts/sentiment_analysis
user_id: null
version: 2
